#! /usr/bin/bash

# Project accounting
export CESM_ACCOUNT=nn9373k
export PROJECT=nn9373k
# CLM paths
export CTSMROOT=${HOME}/ctsm_fates_emerald
export CIMEROOT=$CTSMROOT/cime
# Environment variables
export INC_NETCDF=/cluster/software/VERSIONS/netcdf.intel-4.3.3.1/
export LIB_NETCDF=/cluster/software/VERSIONS/netcdf.intel-4.3.3.1/
export NETCDF_ROOT=/cluster/software/VERSIONS/netcdf.intel-4.3.3.1
# Input
export CESM_DATA=/cluster/shared/noresm/inputdata
export MYCTSMDATA=$USERWORK/inputdata
export REG_DATA=/cluster/projects/nn9373k/data_regional_SBS
export root_frc=/cluster/shared/noresm/inputdata/atm/datm7
# Model components (compset)
export compset=I2000Clm50SpGs # $CTSMROOT/cime/scripts/query_config --compsets clm
# Domain info
export GRIDNAME=0.25_SBS
export ATMDOM=domain.0.25x0.25_SBS.nc
# Case folder
export case_name=${compset}_${GRIDNAME}
export casedir=~/cases/$case_name

# Get CLM and externals
if ! [ -d $CTSMROOT ]; then
    module load git/2.23.0-GCCcore-8.3.0
    git clone -b release-clm5.0 https://github.com/NordicESMhub/ctsm.git $CTSMROOT
    cd $CTSMROOT
    ./manage_externals/checkout_externals
fi;

# Link shared input folder to my work folder
if ! [ -d $MYCTSMDATA ]; then
    cd $CIMEROOT/scripts
    ./link_dirtree $CESM_DATA $MYCTSMDATA
fi;

# Create case
if ! [ -d $casedir ]; then
    cd $CIMEROOT/scripts
    ./create_newcase --case $casedir --compset $compset --res CLM_USRDAT --machine fram --run-unsupported --project $CESM_ACCOUNT
fi;

# Modify XML configuration files generated by case creation
cd $casedir
./xmlchange DIN_LOC_ROOT=$MYCTSMDATA
./xmlchange DIN_LOC_ROOT_CLMFORC=$root_frc
./xmlchange ATM_DOMAIN_PATH=$REG_DATA,LND_DOMAIN_PATH=$REG_DATA
./xmlchange ATM_DOMAIN_FILE=$ATMDOM,LND_DOMAIN_FILE=$ATMDOM
./xmlchange CLM_USRDAT_NAME=$GRIDNAME
./xmlchange STOP_OPTION="nyears"
./xmlchange STOP_N=1
./xmlchange NTASKS=16
./xmlchange JOB_WALLCLOCK_TIME="01:40:00"
./xmlchange PROJECT=$CESM_ACCOUNT
./xmlchange RUN_STARTDATE="2000-01-01"
./xmlchange RESUBMIT="0"
./xmlchange DATM_CLMNCEP_YR_ALIGN="2000"
./xmlchange DATM_CLMNCEP_YR_START="2000"
./xmlchange DATM_CLMNCEP_YR_END="2000"
./xmlchange DOUT_S="FALSE"
./xmlchange GMAKE_J="8"

# Case setup
./case.setup

# Add surface data to user namelist
cat << EOF > user_nl_clm
fsurdat="$REG_DATA/surfdata_0.25_SBS_hist_16pfts_Irrig_CMIP6_simyr2000_c191002.nc"
hist_nhtfrq=-24
EOF
# If restart file is available from spin-up ($RESTART), add: finidat="$RESTART"

# Preview
./preview_run

# Compile
#./case.build --clean
./case.build

# Run
./case.submit

# Check output files
ll $USERWORK/noresm/$case_name/run/${case_name}.clm2.h0.*.nc

# View slurm log
more $casedir/${case_name}.run 
